### ISSUE TITLE
Find scripts relative to self

### ISSUE THREAD

**Issue by kpu** [paracrawl/Domain_Adaptation#1]
Rather than requiring user to specify a command line argument with the path to scripts, use `__file__` to find itself, then other scripts relative to that.

**Comment by dionwiggins** [comment]
Addressed in latest code.

**Comment by kpu** [comment]
Requiring the user to have the code in the current working directory is not fully addressing this issue.  
https://github.com/paracrawl/Domain_Adaptation/blob/master/lib/FullProcess.py#L79
https://stackoverflow.com/questions/4934806/how-can-i-find-scripts-directory-with-python/5475224#5475224

**Comment by dalisola** [comment]
Thank you for suggestion, i used  __file__
