### ISSUE TITLE
Run out of RAM?

### ISSUE THREAD

**Issue by kpu** [paracrawl/Domain_Adaptation#10]
Does LadderXMLfile parse lazily or is this going to load the entire XML into RAM?

https://github.com/paracrawl/Domain_Adaptation/blob/cf06a0e0bb7257d4747fe3d08bac96dbac8a4c5f/P3_DD_Extract.py#L51

**Comment by dionwiggins** [comment]
Updated to stream.

**Comment by kpu** [comment]
The issue can be closed when the master branch is fixed.

**Comment by dalisola** [comment]
issue has been solved on ExtractMatchedDomainData.py
