### ISSUE TITLE
More accessible introduction

### ISSUE THREAD

**Issue by wwaites** [paracrawl/Domain_Adaptation#11]
When I read the beginning of `README.md`, if I don't already know what Domain Adaptation is, the introduction isn't super helpful. Who is the audience? What is the software good for? Why would I want it? What can I expect to be able to do or learn if I read the rest of the document? These are questions that should be answered in the first few sentences of the introduction.

**Comment by dionwiggins** [comment]
Added a lay-person introduction to Domain Adaptation
