### ISSUE TITLE
Start with a worked example

### ISSUE THREAD

**Issue by wwaites** [paracrawl/Domain_Adaptation#12]
After the introduction, a brief explanation of the fact that there are different tools. The diagram at the beginning of Processes and Tools is helpful. But it is not introduced or explained very much. Immediately afterwards there is thorough documentation of the different tools and all of their command line arguments. This is also useful but would usefully come later once I know what each piece does and have seen a simple example. There are examples but they are interspersed with the detailed documentation. It's too easy to get lost without some more orientation at the beginning.

**Comment by dionwiggins** [comment]
Updated to provide more detail.
