### ISSUE TITLE
Table of Contents in README.md

### ISSUE THREAD

**Issue by wwaites** [paracrawl/Domain_Adaptation#15]
The README.md is fairly long. Perhaps it can be separated into different documents (with links between them). A good way to start this would be with a table of contents. See also #11 as this can help with orientation and knowing what to expect from the document.

**Comment by dionwiggins** [comment]
Thanks for the feedback. I will have my team review and update accordingly. This is our first doc of this kind and still getting the hang of formats and norms. Tips like these are very helpful.
