### ISSUE TITLE
Config file default doesn't make sense outside Omniscien

### ISSUE THREAD

**Issue by kpu** [paracrawl/Domain_Adaptation#16]
The default config file is a bunch of custom paths that only exist at Omniscien and are useless to general users.  Why is it optional?  Reading sequentially from the beginning, the user is not aware of this problem until near the end.  

The config file is really more of system setup with paths where tools are installed.  Perhaps the install instructions should say to create such a config file:
https://github.com/paracrawl/Domain_Adaptation/blob/master/INSTALL.md

**Comment by amirkamran** [comment]
Also the config file is not loaded in the code as key:value pairs. It is being loaded as ordered list.

**Comment by dionwiggins** [comment]
Resolved by most recent updates.
