### ISSUE TITLE
Reduce dependency from Moses to preprocess

### ISSUE THREAD

**Issue by kpu** [paracrawl/Domain_Adaptation#2]
It looks like you're using the Moses preprocessor only.  Here's a lighter version already in ParaCrawl projects: https://github.com/kpu/preprocess/

**Comment by dionwiggins** [comment]
Thanks. 
 
Also noted the comments in the call agenda and will get Dali to revise the code accordingly.
 
 
Regards,

Dion Wiggins 
Founder and CTO
Omniscien Technologies

Phone: +66 (8) 7086 3353
Fax: +66 (2) 662 4728, +66 (2) 662 4727
Skype: dionwiggins
Email: dion.wiggins@omniscien.com
Web: http://www.omniscien.com
 
NOTICE: This e-mail (including all information transmitted with it) is for the intended addressee only. It may contain information that is confidential, proprietary and/or legally privileged. No confidentiality, ownership right or privilege is waived or lost by any mistransmission, redirection or interception.  No one other than the intended addressee may read, print, store, copy, forward or act in reliance upon this e-mail.  If you are not the intended addressee: (a) any use, dissemination, printing or copying of this e-mail is strictly prohibited and may be a breach of confidence, and (b) kindly notify the sender by e-mail immediately and delete and destroy all copies of this e-mail in your possession.

**Comment by dionwiggins** [comment]
Addressed in the latest code.
