### ISSUE TITLE
Sleeping?

### ISSUE THREAD

**Issue by kpu** [paracrawl/Domain_Adaptation#23]
Do I want to know why there are sleeps between commands?  Does this suggest a larger issue around ensuring files are properly synced/closed?  

https://github.com/paracrawl/Domain_Adaptation/blob/cbd4c9109fff2e4a3978f84165df4552b67b1810/lib/FullProcess.py#L80

**Comment by dalisola** [comment]
No ,There is no issue , update already in FullProcess
