### ISSUE TITLE
Why catch an informative exception to throw a generic one?  

### ISSUE THREAD

**Issue by kpu** [paracrawl/Domain_Adaptation#28]
https://github.com/paracrawl/Domain_Adaptation/blob/432916d54f537342bcffb30f4968c2e19a5be98e/scripts/FullProcess.py#L92
Just makes it harder to know what the error is.

**Comment by dalisola** [comment]
You are right (even the error is catched from the previous checking ), I commit again and the errors goes to stderr.Thank you
