### ISSUE TITLE
The output should not be parallel?

### ISSUE THREAD

**Issue by ZJaume** [paracrawl/Domain_Adaptation#34]
Hi,

I ran the FullProcess with Paracrawl as pool data and some data from news-crawl as domain data for English-Spanish and the output I'm getting is not parallel.
The command was:
```
python scripts/FullProcess.py -dn news -sl en -tl es -domain news -pool pooldata -out out -working_dir work -threshold 0.5
```

And the result was:
```bash
$ cat out/en/paracrawl6.txt
Kristine - Public profile - Catena Cycling
$ out/es/paracrawl6.txt
Increíble , pero cierto .
$ grep -n 'Kristine - Public' pooldata/en/paracrawl6.txt
41336:Kristine - Public profile - Catena Cycling
$ grep -n 'Increíble, pero' pooldata/es/paracrawl6.txt
20668:Increíble, pero cierto.
```

As far as I understand, the output should be a bilingual parallel subset of the pool data that match the threshold or ratio criteria.
Maybe I've misunderstood something.

**Comment by phikoehn** [comment]
I just run the script again on my data and it is working fine for me. Can you send me the files you are using so I can check it on your files?

**Comment by ZJaume** [comment]
Sorry, it was my fault. I changed a couple of lines in the code and I didn't remember to delete working_dir after discarding the code changes, now it's working.
