### ISSUE TITLE
Could the output be untokenized?

### ISSUE THREAD

**Issue by ZJaume** [paracrawl/Domain_Adaptation#35]
With SentencePiece being widely used in NMT, tokenized output it's more an obstacle than a benefit, I think. Could the output be untokenized or add an option to choose between tokenized and untokenized? I think tokenized pool-data should be used only for LM scoring, and use the untokenized sentences and the scores to produce the output.

**Comment by phikoehn** [comment]
I added the option "-output_raw" to the FullProcess script. For the SelectData script, just point to the raw data.

**Comment by ZJaume** [comment]
Tested and working! :+1:
