### ISSUE TITLE
User-specified tokenizer

### ISSUE THREAD

**Issue by kpu** [paracrawl/Domain_Adaptation#7]
The standard in ParaCrawl is that the user can specify a tokenizer rather than it being hard-coded into the packages.  This way some user can handle Chinese etc.  
I suspect this will be moot once integrated into bitextor since it should be tokenizing for you anyway.

**Comment by dionwiggins** [comment]
Any tokenizer can be used. See https://github.com/paracrawl/Domain_Adaptation#tokenizer
