### ISSUE TITLE
Be more flexible about python version

### ISSUE THREAD

**Issue by kpu** [paracrawl/Domain_Adaptation#8]
Don't assume everybody has Python 3.6 installed.  They might have 3.7 and no 3.6.  Currently the code calls python3.6.

**Comment by dionwiggins** [comment]
Addressed in the latest code.

**Comment by kpu** [comment]
https://github.com/paracrawl/Domain_Adaptation/blob/cbd4c9109fff2e4a3978f84165df4552b67b1810/lib/FullProcess.py#L79

**Comment by amirkamran** [comment]
Also, in the requirements.txt there is logging dependency that does not compile for with pip3. Isn't logging library by default part of python3.

**Comment by dalisola** [comment]
Its work now with python3 no need for logging
